In [2]:
#alias
#how to install a package
!pip install numpy
import numpy as np

In [6]:
np.asarray([9])

array([9])

In [9]:
a = np.array([1,2,3,4,5])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(5,)


In [20]:
b = np.array([[1],[2],[3],[4],[5]])
print(b.shape)
c = np.array([[1,2],[2,3],[3,4],[4,5],[5,6]])
print(c.shape)

(5, 1)
(5, 2)


In [23]:
d = np.array([[[1],[2]],[[3],[4]]])
print(d.shape)

(2, 2, 1)


In [33]:
a = np.zeros((3,3))
print(a)

b = np.ones((3,4))
print(b)

c = np.full((3,4),5)
print(c)

d = np.eye(4)
print(d)

random = np.random.random((3,2))
print(random)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.51755008 0.50194872]
 [0.18377548 0.14118771]
 [0.16080962 0.08449372]]


In [34]:
c = np.array([[1,2],[2,3],[3,4],[4,5],[5,6]])
c[1][0] = 10000
print(c)

[[    1     2]
 [10000     3]
 [    3     4]
 [    4     5]
 [    5     6]]


In [40]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,2],[3,4]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [43]:
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))

[[2 4]
 [6 8]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


In [45]:
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))

[[ 1  4]
 [ 9 16]]
[[ 1  4]
 [ 9 16]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]


In [48]:
print(x)
print(5+x)
print(5-x)
print(5*x)
print(x/5)

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[4 3]
 [2 1]]
[[ 5 10]
 [15 20]]
[[0.2 0.4]
 [0.6 0.8]]


In [61]:
op = np.array(list(map(int,input().split())))
print(op)

1 2 3 4 56 7
[ 1  2  3  4 56  7]


In [63]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a.dot(b))

40


In [64]:
2+6+12+20

40

In [75]:
c = np.stack((a,b),axis=0)

In [76]:
print(c)
print(c.shape)

[[1 2 3 4]
 [2 3 4 5]]
(2, 4)


In [79]:
print(a)
print(a.shape)

[1 2 3 4]
(4,)


In [88]:
d = a.reshape((-1,2))
print(d)
print(d.shape)

[[1 2]
 [3 4]]
(2, 2)


In [93]:
p = np.asarray([1,2,3,4,5,6,7,8,9,0])
print(p)

[1 2 3 4 5 6 7 8 9 0]


In [107]:
p[4:-1]

array([5, 6, 7, 8, 9])

In [110]:
p[::-1]

array([0, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [115]:
l = np.arange(11)
print(l)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [144]:
# np.random.seed(2)
np.random.shuffle(l)
print(l)

[ 5  9  3  1  0  4  8  2  7  6 10]


In [5]:
np.random.seed(12)
arr = np.random.randint(5,10,4)
print(arr)

[8 8 6 7]


In [128]:
np.random.choice([1,4,5,26,84,29])

5

In [1]:
import random